### ISSUE TITLE
App crash after update

### ISSUE THREAD

**Issue by 4-life** [yogeshpaliyal/KeyPass#705]
**Describe the bug**
App crash after update with an error:

```
javax.crypto.IllegalBlockSizeException
at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:613)
at javax.crypto.Cipher.doFinal(Cipher.java:2056)
at t7.c.a(SourceFile:1)
at t7.v.h(SourceFile:34)
at m3.h0.h(SourceFile:1)
at m3.h0.i(SourceFile:111)
at m3.h0.e(SourceFile:1)
at m3.h0.g(SourceFile:1)
at m3.r.g(SourceFile:81)
at m3.r.b0(SourceFile:13)
at m3.m.g(SourceFile:93)
at j9.a.o(SourceFile:1)
at aa.f0.run(SourceFile:1)
at kotlinx.coroutines.internal.e.run(Unknown Source:11)
at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
Suppressed: androidx.datastore.preferences.protobuf.m1: [androidx.compose.ui.platform.q1@71beed1, f0.e@4e8d36, q1{Cancelling}@e3cc437, s0@d327da4]
Caused by: android.security.KeyStoreException: Invalid input length (internal Keystore code: -21 message: In KeystoreOperation::finish

Caused by:
    0: In finish: KeyMint::finish failed.
    1: Error::Km(ErrorCode(-21))) (public error code: 13 internal Keystore code: -21)
at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
```

**To Reproduce**
1. Install app
2. Update it
3. Open app

**Expected behavior**
App runs without crashing

App Version: 1.4.21
Brand Name: Redmi
Manufacturer Name: Xiaomi
Device Name: Redmi Note 10S
Device API Version: 33

**Comment by yogeshpaliyal** [comment]
App is released

**Comment by 4-life** [comment]
@yogeshpaliyal now works well. Thanks
