### ISSUE TITLE
the app is crash

### ISSUE THREAD

**Issue by kikass47x** [yogeshpaliyal/KeyPass#719]
the app is crash The instant that open and i can't rolling back 

with report

javax.crypto.IllegalBlockSizeException
at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:613)
at javax.crypto.Cipher.doFinal(Cipher.java:1939)
at t7.v.h(SourceFile:63)
at m3.h0.h(SourceFile:1)
at m3.h0.i(SourceFile:111)
at m3.h0.e(SourceFile:1)
at m3.h0.g(SourceFile:1)
at m3.r.g(SourceFile:81)
at m3.r.b0(SourceFile:13)
at m3.m.g(SourceFile:93)
at j9.a.o(SourceFile:1)
at aa.f0.run(SourceFile:1)
at kotlinx.coroutines.internal.e.run(Unknown Source:11)
at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
Suppressed: androidx.datastore.preferences.protobuf.m1: [androidx.compose.ui.platform.q1@5200746, f0.e@6fe9d07, q1{Cancelling}@8ab2e34, s0@92eb45d]
Caused by: android.security.KeyStoreException: Invalid input length (internal Keystore code: -21 message: In KeystoreOperation::finish

Caused by:
    0: In finish: KeyMint::finish failed.
    1: Error::Km(ErrorCode(-21))) (public error code: 13 internal Keystore code: -21)
at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
... 14 more

App Version from Build: 1.4.22
Current App Version: Not able to fetch
Previous App Version: Not able to fetch
Installed from: com.miui.packageinstaller
Brand Name: Xiaomi
Manufacturer Name: Xiaomi
Device Name: 2204122SC
Device API Version: 33

**Comment by yogeshpaliyal** [comment]
Please clear app data and try again or uninstall and install

**Comment by kikass47x** [comment]
the problem I can't clear data because i don't have a backup and i try clearing the cash without luck iam trying to downgrade the app by adb to get the account
________________________________

**Comment by tmachyshyn** [comment]
@yogeshpaliyal  I have the same problem and I don't have a backup. 
It's better to describe your disclaimer: `Please take a backup before updating to new app` in every release notes. 
Perhaps, one of the solution is to downgrade to v1.4.20 or v1.4.19. Please let me know how to download these versions since they are not available in f-droid?

**Comment by yogeshpaliyal** [comment]
You can download 1.4.18 from fdroid and downgrade to that version

**Comment by kikass47x** [comment]
thank very much i did it but by adb to downgrade
________________________________

**Comment by yogeshpaliyal** [comment]
Can you please share the commands so others can follow the same steps, would be very useful

**Comment by kikass47x** [comment]
https://www.makeuseof.com/downgrade-android-app-with-adb/

from this website with the steps
________________________________

**Comment by yogeshpaliyal** [comment]
Thanks @kikass47x
